# Generated by Django 5.2.8 on 2025-12-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("visitante", "Visitante"),
                    ("miembro", "Miembro"),
                    ("colaborador", "Colaborador"),
                ],
                default="visitante",
                max_length=20,
            ),
        ),
    ]
